# Generated by Django 4.1.3 on 2022-11-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('o_title', models.CharField(max_length=512)),
                ('is_serie', models.BooleanField()),
                ('season', models.IntegerField(blank=True, default=0, null=True)),
                ('episode', models.IntegerField(blank=True, default=0, null=True)),
                ('year', models.IntegerField(default=0)),
                ('directors', models.TextField(blank=True, default='', null=True)),
                ('actors', models.TextField(blank=True, default='', null=True)),
                ('banners', models.TextField(blank=True, default='', null=True)),
                ('posters', models.TextField(blank=True, default='', null=True)),
                ('provider_name', models.TextField(blank=True, default='', null=True)),
                ('language', models.CharField(max_length=256)),
                ('fsk', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(blank=True, default=None, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_mal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WatchingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
