# Generated by Django 4.1.3 on 2022-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_serie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='season',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(default=0),
        ),
    ]
