# Generated by Django 4.1.3 on 2022-11-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_movie_imdb_id_movie_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
